M48
; DRILL file {KiCad 7.0.9} date Tuesday, December 26, 2023 at 12:13:05 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-26T12:13:05+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.078Y-2.1146
X4.078Y-4.7684
X6.7401Y-2.1187
X6.7495Y-4.7871
T0
M30
